### PR TITLE
Update painter_controller.dart

### PR DESCRIPTION
**Pull request by ibrahim-cse**

### CODE REVIEW

**Comment by omarhurani** [comment]
Can you please explain what this is supposed to add/fix?

**Comment by ibrahim-cse** [comment]
I want to add a redo button functionality. Not sure the index is current
but would be a great help can add it in your way. Thanks

**Comment by omarhurani** [comment]
The feature is already present on the 1.0.0 branch

**Comment by ibrahim-cse** [comment]
Thanks a lot man.

**Pull request closed without merging**
